### ISSUE TITLE
Rails 5 incompatibility

### ISSUE THREAD

**Issue by kdiogenes** [SchemaPlus/schema_plus_foreign_keys#12]
I'm having a problem using this gem with Rails 5.1.0.beta1. I open an issue there https://github.com/rails/rails/issues/28192, but I think the problem is with schema_plus_foreign_keys

While using this gem, when I execute `Event.last.administrators.to_sql` in a class like this:

```ruby
class Event < ApplicationRecord
  has_and_belongs_to_many :administrators, class_name: User
end
```
I get the following:
`"SELECT \"users\".* FROM \"users\" WHERE \"users\".\"event_id\" = 1"`

Instead of:
`"SELECT \"users\".* FROM \"users\" INNER JOIN \"events_users\" ON \"users\".\"id\" = \"events_users\".\"user_id\" WHERE \"events_users\".\"event_id\" = 1"`

**Comment by urkle** [comment]
This gem only handles the migrations of foreign keys in a nice manner. It does not affect how AR generates SQL queries. 

Also there is a new update to this gem that fully supports Rails 5.2
