### ISSUE TITLE
Cannot pass options to add_foreign_key

### ISSUE THREAD

**Issue by stenver** [SchemaPlus/schema_plus_foreign_keys#2]
https://github.com/SchemaPlus/schema_plus_foreign_keys/blob/6e2e34802a57fab771977a45f5aa0d6327262038/lib/schema_plus/foreign_keys/active_record/connection_adapters/abstract_adapter.rb#L26

Its not possible to add options when using the new syntax of `add_foreign_key`

i.e. this fails:

```
add_foreign_key 'archive.sub_engagement_logs', 'site.sites', name: 'some lol'
```

**Comment by ronen** [comment]
Odd.  It ought to work fine, it's used that way in various places in the specs.  Are you sure you don't have something else going on?  

The line of code that checks for `args.length == 2` happens after `options = args.extract_options!`

**Comment by stenver** [comment]
You are right. I looked into it futher and the problem is rather that the method `foreign_key_column_for` fails to return the correct column name for the foreign key. Thats because I use multiple schemas. it can probably be fixed by updating active record. Sorry for the confusion, closing this.

**Comment by ronen** [comment]
> `foreign_key_column_for` fails to return the correct column name for the foreign key. Thats because I use multiple schemas. it can probably be fixed by updating active record.

maybe that's something else to fix in schema_plus_multischema?

**Comment by stenver** [comment]
Good idea. I will make an issue there
